blog/urls.py
from django.urls import path
from blog.views import(
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
)

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit', edit_blog_view, name="edit"),

]

simplewebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


from FrontEnd.views import (
    home_screen_view,
)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('admin/', admin.site.urls),
    path('account/', account_view, name="account"),    
    path('blog/', include('blog.urls', 'blog')),    
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),

    # path('account/', include('django.contrib.auth.urls')),
    
    # Password reset 
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
        name='password_change_done'),
    
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
        name='password_change'),
    
    path('password_reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
        name='password_reset_done'),
    
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.utils import timezone


def upload_location(instance, filename, **kwargs):
    file_path = 'blog/{author_id}/{title}-{filename}'.format(
        author_id = str(instance.author.id), 
        title = str(instance.title),
        filename = filename
    )
    return file_path 

class BlogPost(models.Model):
    title             = models.CharField(max_length=50, null=False, blank=False)
    body              = models.TextField(max_length=5000, null=False, blank=False)
    image             = models.ImageField(upload_to=upload_location, null=False, blank=False)
    created_at        = models.DateTimeField(default=timezone.now, verbose_name="created at")
    updated_at        = models.DateTimeField(default=timezone.now, verbose_name="updated at")
    author            = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug              = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title

@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)

def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)

blog/forms.py
from django import forms

from blog.models import BlogPost

class CreateBlogPostForm(forms.ModelForm):
    
    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']

class UpdateBlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']
    
    def save(self, commit=True):
        blog_post = self.instance
        blog_post.title = self.cleaned_data['title']
        blog_post.body = self.cleaned_data['body']

        if self.cleaned_data['image']:
            blog_post.image = self.cleaned_data['image']
        
        if commit:
            blog_post.save()
        
        return blog_post

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404 
from django.db.models import Q
from django.http import HttpResponse
from blog.models import BlogPost
from blog.forms import CreateBlogPostForm, UpdateBlogPostForm
from account.models import Account

# Create your views here.

def create_blog_view(request):
    
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')

    form = CreateBlogPostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.save()
        form = CreateBlogPostForm()
    
    context['form'] = form

    return render(request, "blog/create_blog.html", context)

def detail_blog_view(request, slug):
    
    context = {}

    blog_post = get_object_or_404(BlogPost, slug=slug)
    context['blog_post'] = blog_post

    return render(request, 'blog/detail_blog.html', context)

def edit_blog_view(request, slug):
    
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect("must_authenticate")
    
    blog_post = get_object_or_404(BlogPost, slug=slug)
    
    if blog_post.author != user:
        return HttpResponse("You are not the author of that post.")

    if request.POST:
        form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=blog_post)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = "Updated"
            blog_post = obj

    form = UpdateBlogPostForm(
            initial = {
                    "title": blog_post.title,
                    "body": blog_post.body,
                    "image": blog_post.image,
            }
        )
    
    context['form'] = form
    return render(request, 'blog/edit_blog.html', context)


def get_blog_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        posts= BlogPost.objects.filter(
                Q(title__icontains=q) |
                Q(body__icontains=q)
        ).distinct()

        for post in posts:
            queryset.append(post)
    
    return list(set(queryset))

blog/templates/blog/create_blog.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
    .create-form {
        width: 100%;
        max-width: 100%;
        padding: 15px;
        margin: auto;
    }

        .submit-button{
            max-width: 200px;
        }
</style>

<div class="container">
    <div class="row">
        <div class="col-lg-7 offset-lg-1">
            <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

                <!-- title -->
                <div class="form-group">
                    <label for="id_title">Title</label>
                    <input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
                </div>

                <!-- Body -->
                <div class="form-group">
                    <label for="id_body">Content</label>
                    <textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." required></textarea>
                </div>

                <!-- Image -->
                <div class="form-group">
                    <label for="id_image">Image</label>
                    <input  type="file" name="image" id="id_image" accept="image/*" required>
                </div>

                <!-- Submit btn -->
                <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
            </form>	
        </div>
    </div>
</div>

{% endblock content%}

blog/templates/blog/detail_blog.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
    .card{
        max-width: 700px;
    }

    .container{
        padding: 20px;
    }
</style>

<div class="container">
    <div class="row">

        <!-- Blog post -->
        <div class="card m-auto">
            <img class="card-img-top" src="{{blog_post.image.url}}">
            <div class="card-body my-2">
                <h2 class="card-title">{{blog_post.title}}</h2>
                <p class="card-text">{{blog_post.body|safe}}</p>
                {% if blog_post.author == request.user %}
                    <a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-primary">Update</a>
                {% endif %}
            </div>
            <div class="card-footer text-muted">
                Updated on {{blog_post.date_updated}} by {{blog_post.author}}
            </div>
        </div>
        <!-- End Blog post -->
    </div>
</div>

{% endblock content %}

blog/templates/blog/edit_blog.html
{% extends 'base.html' %}


{% block content %}
<style type="text/css">

    .create-form {
	width: 100%;
	max-width: 100%;
	padding: 15px;
	margin: auto;
    }

    .submit-button{
    max-width: 200px;
    }

	.image {
	opacity: 1;
	transition: .5s ease;
	backface-visibility: hidden;
	}

	.middle {
	transition: .5s ease;
	opacity: 0;
	position: absolute;
	text-align: center;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
        text-align: center;
    	cursor:pointer;
	}

	.image-group:hover .image {
	opacity: 0.3;
	}

	.image-group:hover .middle {
	opacity: 1;
	}

	.text {
	margin: auto;
	background-color: #4CAF50;
	color: white;
	font-size: 15px;
	padding: 15px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." 
					required>{{form.initial.body}}</textarea>
				</div>

				<!-- Image -->
				<div class="form-group image-group" id="id_image_group">
					<img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
     				<div class="middle">
					<div class="text">Change image</div>
					</div>
				</div>
				<input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">
				

				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>	
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
        document.getElementById('id_image_file').click();
    };

	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_image_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}
</script>

{% endblock content %}